services:
  python3:
    restart: always
    build: .
    # working_dir: /workspace/src
    tty: true
    environment:
      - PYTHONPATH=/workspace
    volumes:
      # - ./src:/workspace/src
      # - ./results:/workspace/results
      # - ./app:/workspace/app
      - ./:/workspace
